// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrWZQLCxa29Be43uccO9_PapC3xcjJ4RQ',
    appId: '1:599020531493:web:dbf69d8435dcd995e6b4cc',
    messagingSenderId: '599020531493',
    projectId: 'linkhub-515bf',
    authDomain: 'linkhub-515bf.firebaseapp.com',
    storageBucket: 'linkhub-515bf.firebasestorage.app',
    measurementId: 'G-123ZXELE19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCL8eQuduHCXpiiXSujRVCyl9pKH3H42I',
    appId: '1:599020531493:android:ef23a48da6c849f5e6b4cc',
    messagingSenderId: '599020531493',
    projectId: 'linkhub-515bf',
    storageBucket: 'linkhub-515bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd0FWi6xRGoSguS1XsmJJguloTkT-RbaQ',
    appId: '1:599020531493:ios:724ebaf67a6bac67e6b4cc',
    messagingSenderId: '599020531493',
    projectId: 'linkhub-515bf',
    storageBucket: 'linkhub-515bf.firebasestorage.app',
    iosBundleId: 'com.example.linkhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrWZQLCxa29Be43uccO9_PapC3xcjJ4RQ',
    appId: '1:599020531493:web:11f1c65dfa8dfee8e6b4cc',
    messagingSenderId: '599020531493',
    projectId: 'linkhub-515bf',
    authDomain: 'linkhub-515bf.firebaseapp.com',
    storageBucket: 'linkhub-515bf.firebasestorage.app',
    measurementId: 'G-3LFJPPQVPV',
  );
}
